#!/usr/bin/env node
/**
 * Renders the three legal pages from app/src/lib/legal.js.
 *
 * The text was written into three HTML files by hand, and the app linked out to
 * them. A correction could then land on the website and not in the app, for
 * documents about someone's bank data. One source, two renderers.
 *
 *   node scripts/build-legal.mjs        (run from the repo root)
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { LEGAL, LEGAL_UPDATED, ENTITY, LEGAL_EMAIL } from "../app/src/lib/legal.js";

const esc = (s) => s;   // the source is our own copy and already carries its markup

const block = (b) => {
  if (b.p) return `    <p>${b.p}</p>`;
  if (b.ul) return `    <ul>\n${b.ul.map((li) => `      <li>${li}</li>`).join("\n")}\n    </ul>`;
  if (b.note) return `    <div class="note"><b>${b.note.h}</b><p>${b.note.p}</p></div>`;
  if (b.table) {
    const { head, rows } = b.table;
    return `    <table>\n      <tr>${head.map((h) => `<th>${h}</th>`).join("")}</tr>\n` +
      rows.map((r) => `      <tr>${r.map((c) => `<td>${c}</td>`).join("")}</tr>`).join("\n") +
      `\n    </table>`;
  }
  return "";
};

const page = (key, doc) => {
  const toc = doc.sections
    .filter((s) => !(s.blocks.length === 1 && s.blocks[0].note))
    .map((s) => `<a href="#${s.id}">${s.h}</a>`).join("");

  const body = doc.sections.map((s, i) => {
    const summaryOnly = i === 0 && s.blocks.length === 1 && s.blocks[0].note;
    const inner = s.blocks.map(block).join("\n");
    return summaryOnly ? inner : `    <h2 id="${s.id}">${s.h}</h2>\n${inner}`;
  }).join("\n\n");

  return `<!doctype html>
<html lang="en" data-t="light"><head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
<title>${doc.title} &middot; Brasstally</title>
<meta name="description" content="${doc.lede.replace(/<[^>]+>/g, "").slice(0, 155)}"/>
<link rel="canonical" href="https://www.brasstally.com/${key === "data" ? "data" : key}"/>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"/>
<style>
/* Generated by scripts/build-legal.mjs from app/src/lib/legal.js. Edit there. */
:root{--gutter:clamp(28px, 6.2vw, 64px)}
html[data-t="light"]{--bg:#FAF9F7;--surface:#FFF;--sunk:#F5F3F0;--line:#EDEAE5;
 --text:#1C1917;--muted:#5A534E;--faint:#8A827B;--accent:#F59E0B;--accentText:#A9620A;
 --credit:#08805A;--debit:#C4442F;--glass:rgba(250,249,247,.86)}
html[data-t="dark"]{--bg:#100E0C;--surface:#1A1714;--sunk:#221E1A;--line:#2A2521;
 --text:#F5F1EC;--muted:#B0A79F;--faint:#877E76;--accent:#FBBF24;--accentText:#FBBF24;
 --credit:#34D399;--debit:#FB7185;--glass:rgba(16,14,12,.86)}
*{box-sizing:border-box;margin:0}
html{scroll-behavior:smooth;scroll-padding-top:90px;-webkit-text-size-adjust:100%}
body{background:var(--bg);color:var(--text);font-family:'Inter',system-ui,-apple-system,sans-serif;
 font-size:17px;line-height:1.68;letter-spacing:-.011em;-webkit-font-smoothing:antialiased;overflow-x:clip}
a{color:var(--accentText);text-decoration:none}
a:hover{text-decoration:underline}
.wrap{max-width:760px;margin:0 auto;padding-left:28px;padding-right:28px;
 padding-left:var(--gutter);padding-right:var(--gutter)}
@supports (padding: env(safe-area-inset-left)){
  .wrap{padding-left:calc(var(--gutter) + env(safe-area-inset-left));
        padding-right:calc(var(--gutter) + env(safe-area-inset-right))}
}
/* The header sat under the status bar in a home-screen install, because a
   standalone web app owns the whole display and nothing here respected the top
   inset. It does now, and the row is 44px so Home is reachable. */
nav{position:sticky;top:0;z-index:50;background:var(--glass);
 backdrop-filter:blur(16px) saturate(1.3);-webkit-backdrop-filter:blur(16px) saturate(1.3);
 border-bottom:1px solid var(--line);padding-top:env(safe-area-inset-top, 0px)}
.navin{display:flex;align-items:center;gap:10px;min-height:56px}
.navin b{font-size:17px;font-weight:600;letter-spacing:-.02em}
.navin .sp{flex:1}
.navin a.home{font-size:15px;color:var(--muted);min-height:44px;display:inline-flex;align-items:center;padding:0 4px}
header.page{padding-top:36px;padding-bottom:6px}
.kicker{font-size:15px;font-weight:600;color:var(--accentText);margin-bottom:10px}
h1{font-size:clamp(29px,7.4vw,38px);font-weight:600;letter-spacing:-.03em;line-height:1.16;margin-bottom:12px}
.meta{font-size:15px;color:var(--faint)}
.lede{font-size:17.5px;color:var(--muted);margin-top:14px}
main{padding-top:14px;padding-bottom:calc(80px + env(safe-area-inset-bottom, 0px))}
h2{font-size:21px;font-weight:600;letter-spacing:-.02em;margin:36px 0 8px;scroll-margin-top:96px}
p{color:var(--muted);margin-bottom:13px}
strong{color:var(--text);font-weight:600}
ul{margin:0 0 14px;padding:0;list-style:none}
li{position:relative;padding-left:22px;margin-bottom:8px;color:var(--muted)}
li:before{content:"";position:absolute;left:4px;top:11px;width:6px;height:6px;border-radius:50%;background:var(--accent)}
li strong{color:var(--text)}
table{width:100%;border-collapse:collapse;margin:6px 0 18px;font-size:15.5px}
th{text-align:left;font-weight:600;color:var(--faint);padding:8px 12px 8px 0;
 border-bottom:1px solid var(--line);font-size:14.5px}
td{padding:10px 12px 10px 0;border-bottom:1px solid var(--line);color:var(--muted);vertical-align:top}
td strong{color:var(--text)}
/* A multi-column table cannot be read on a phone, so each cell gets its own
   labelled line rather than a sideways scroll through a legal document. */
@media (max-width:640px){
  table,tbody,tr,td,th{display:block;width:100%}
  thead{display:none}
  tr{background:var(--sunk);border-radius:14px;padding:14px;margin-bottom:10px}
  td{border:0;padding:0 0 10px}
  td:last-child{padding-bottom:0}
  td:before{content:attr(data-l);display:block;font-size:13px;color:var(--faint);margin-bottom:2px}
}
.note{background:var(--sunk);border-radius:16px;padding:20px;margin:18px 0}
.note b{display:block;font-size:16.5px;color:var(--text);margin-bottom:5px}
.note p{margin-bottom:0;font-size:16px}
.toc{background:var(--surface);border-radius:16px;padding:18px 20px;margin:22px 0;
 box-shadow:0 1px 2px rgba(28,25,23,.05),0 8px 22px -14px rgba(28,25,23,.14)}
.toc div{font-size:14.5px;color:var(--faint);margin-bottom:8px}
.toc a{display:block;padding:9px 0;font-size:16px;border-top:1px solid var(--line);min-height:44px}
footer{border-top:1px solid var(--line);padding-top:22px;margin-top:40px;font-size:15px;color:var(--faint)}
footer a{margin-right:16px}
@media print{nav{position:static}.toc{display:none}body{background:#fff;font-size:10.5pt}}
</style>
<script>document.documentElement.setAttribute("data-t","light");</script>
</head>
<body>
<nav><div class="wrap navin">
  <svg width="22" height="22" viewBox="0 0 24 24" fill="none" aria-hidden="true">
    <path d="M4 9.5h11" stroke="var(--credit)" stroke-width="2.6" stroke-linecap="round"/>
    <path d="M4 15h8" stroke="var(--debit)" stroke-width="2.6" stroke-linecap="round"/>
    <path d="M18.5 6.5l-1.4 11" stroke="var(--accent)" stroke-width="2.6" stroke-linecap="round"/>
  </svg>
  <b>Brasstally</b><span class="sp"></span>
  <a class="home" href="/">Home</a>
</div></nav>

<div class="wrap">
  <header class="page">
    <div class="kicker">${doc.kicker}</div>
    <h1>${doc.title}</h1>
    <div class="meta">Last updated ${LEGAL_UPDATED}</div>
    <p class="lede">${doc.lede}</p>
  </header>

  <main>
    <div class="toc"><div>On this page</div>${toc}</div>

${body}

    <footer>
      <a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/data">Your financial data</a><br/><br/>
      Developed by ${ENTITY} in Ontario, Canada. Questions about any of this go to
      <a href="mailto:${LEGAL_EMAIL}">${LEGAL_EMAIL}</a>.
    </footer>
  </main>
</div>
</body></html>
`;
};

let n = 0;
for (const [key, doc] of Object.entries(LEGAL)) {
  mkdirSync(`landing/${key}`, { recursive: true });
  let html = page(key, doc);
  // the stacked mobile table needs each cell to know its column
  html = html.replace(/<tr>((?:<th>.*?<\/th>)+)<\/tr>\n((?:\s*<tr>.*?<\/tr>\n?)+)/gs, (m, headRow, bodyRows) => {
    const labels = [...headRow.matchAll(/<th>(.*?)<\/th>/g)].map((x) => x[1]);
    const fixed = bodyRows.replace(/<tr>(.*?)<\/tr>/gs, (row, cells) => {
      let i = 0;
      return "<tr>" + cells.replace(/<td>/g, () => `<td data-l="${labels[i++] ?? ""}">`) + "</tr>";
    });
    return `<tr>${headRow}</tr>\n${fixed}`;
  });
  writeFileSync(`landing/${key}/index.html`, html);
  n += 1;
  console.log(`  landing/${key}/index.html  ${doc.sections.length} sections, ${html.length} bytes`);
}
console.log(`  ${n} pages generated from app/src/lib/legal.js`);
