-- ============================================================
-- Superseded. Nothing to run.
--
-- This added a file path to submit_invoice. That change is now part of 0022,
-- because the first 0022 rolled back in full and had to be re-run anyway, and
-- two files to run in order is one more chance to run only the first.
--
-- Left in place so the numbering does not shift under anyone who already has
-- a record of what they ran.
-- ============================================================
select 'superseded by 0022' as note;
